Q1:Name and handle the exception 
>>> a=3
>>> if a<4:
	a=a/(a-3)
	print(a)

	
Traceback (most recent call last):
  File "<pyshell#4>", line 2, in <module>
    a=a/(a-3)
ZeroDivisionError: division by zero
>>> exception handled:
a=3
try:
    if a<4:
        a=a/(a-3)
except:
    print(a)
output::
>>> 
3
>>> 
Q2:l=[1,2,3]
print(l[3])
output:
>>> 
Traceback (most recent call last):
  File "C:/Python34/ex2.py", line 2, in <module>
    print(l[3])
IndexError: list index out of range
>>> 
try:
    
    
    l=[1,2,3]
except:
    
    
    print(l[3])
    output:
>>> 

Q3:
try:
    raise NameError("Hi there")  # Raise Error
except NameError:
    print ("An exception")
    raise  # To determine whether the exception was raised or not
output:
>>> 
An exception
Traceback (most recent call last):
  File "C:/Python34/ex3.py", line 2, in <module>
    raise NameError("Hi there")  # Raise Error
NameError: Hi there
>>> 
>>> 
Q4:
def AbyB(a , b):
	try:
		c = ((a+b) / (a-b))
	except ZeroDivisionError:
		print ("a/b result in 0")
	else:
		print(c)

# Driver program to test above function
AbyB(2.0, 3.0)
AbyB(3.0, 3.0)
output:
>>> 
-5.0
a/b result in 0
>>> 
Q5:
import error : sir nhi pta...
value error:
try:
    n=int(input("enter a num"))

except ValueError:
    print("u must have to enter a num")
else:
    print(n)
  #IndexError  
  try:
    
    
    l=[1,2,3,56]
except:
    
    
    print(l[8])
   
Q6:
class AgeError():
    try:
        age=int(input("enter age"))
    except ValueError:
        print("enter age as digit")

    while(age<=18):
        try:
            if(age<18):
                raise AgeSmallError
        except AgeSmallError:
            print("age is greater than 18")
print("eneter age is ",age)
        
        
